# Generated by Django 5.1.5 on 2025-01-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
