# Generated by Django 5.1.5 on 2025-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_personne_nom_personne_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='telephone',
        ),
        migrations.AddField(
            model_name='personne',
            name='tel',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(default='', max_length=300, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('SECRETAIRE', 'Secrétaire'), ('PROFESSEUR', 'Professeur'), ('ETUDIANT', 'Étudiant'), ('ELEVE', 'Élève')], max_length=20, verbose_name='Role'),
        ),
    ]
