# Generated by Django 5.1.5 on 2025-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_personne_nom_remove_personne_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=300, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('SECRETAIRE', 'Secrétaire'), ('PROFESSEUR', 'Professeur'), ('ETUDIANT', 'Étudiant'), ('ELEVE', 'Élève')], max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='tel',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
