# Generated by Django 5.1.5 on 2025-02-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_personne_email_alter_personne_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
