# Generated by Django 5.1.5 on 2025-01-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_remove_etablissement_adresse_and_more'),
        ('matieres', '0001_initial'),
        ('utilisateurs', '0003_remove_personne_nom_remove_personne_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='etablissements.etablissement')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='utilisateurs.personne')),
            ],
        ),
    ]
