# Generated by Django 5.1.5 on 2025-01-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_matiere'),
        ('utilisateurs', '0003_remove_personne_nom_remove_personne_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=20)),
                ('evaluation_type', models.CharField(choices=[('test', 'Test'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('participation', 'Participation')], default='test', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='matieres.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='matieres.matiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='utilisateurs.personne')),
            ],
            options={
                'unique_together': {('student', 'matiere', 'evaluation_type', 'date_added')},
            },
        ),
    ]
