# Generated by Django 5.1.5 on 2025-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0003_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='strength',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif'),
        ),
    ]
