# Generated by Django 5.1.5 on 2025-01-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0005_remove_etablissement_adresse_and_more'),
        ('matieres', '0002_matiere'),
        ('utilisateurs', '0003_remove_personne_nom_remove_personne_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('trimestre_1', 'Premier Trimestre'), ('trimestre_2', 'Deuxième Trimestre'), ('trimestre_3', 'Troisième Trimestre'), ('semestre_1', 'Premier Semestre'), ('semestre_2', 'Deuxième Semestre'), ('annuel', 'Annuel')], max_length=20)),
                ('moyenne_generale', models.FloatField(default=0.0)),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='matieres.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='etablissements.etablissement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='utilisateurs.personne')),
            ],
            options={
                'unique_together': {('student', 'period', 'etablissement')},
            },
        ),
    ]
