# Generated by Django 5.1.5 on 2025-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('type_etablissement', models.CharField(choices=[('ecole', 'École'), ('universite', 'Université')], default='ecole', max_length=10)),
                ('decoupage_annuel', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre')], default='trimestre', max_length=10)),
            ],
        ),
    ]
