# Generated by Django 5.1.5 on 2025-01-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
    ]
