# Generated by Django 5.1.5 on 2025-01-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_remove_save_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('ecole', 'École'), ('universite', 'Université')], default='', max_length=10),
        ),
    ]
