# Generated by Django 5.1.5 on 2025-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_alter_etablissement_type_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='nom',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='address',
            field=models.TextField(default='', max_length=300, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nom'),
        ),
    ]
