# Generated by Django 5.1.5 on 2025-01-31 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_remove_etablissement_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
