# Generated by Django 5.1.5 on 2025-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0006_etablissement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name="Code de l'etablissement"),
        ),
    ]
